### ISSUE TITLE
Bug in getFirstError

### ISSUE THREAD

**Issue by haraldglaser** [jlorente/yii2-activerecord-inheritance#2]
Last line of getFirstError() should be:
`return count($errors) ? $errors[0] : null;`
instead of 
`return empty($errors[$attribute]) ? null : $errors[0];`

`$errors` is a numeric array.

**Comment by jlorente** [comment]
You are right. I will fix it.

**Comment by jlorente** [comment]
I have set your code in the trait and now it works correctly. Thank you for the collaboration!
